Makefile.playroom:
	@:

build:
	@musical-patterns-cli build "webpack --config webpack.prod.js"

build_dev:
	@webpack --config webpack.dev.js

start_test:
	@webpack-dev-server --config webpack.test.js --color

start_qa:
	@webpack-dev-server --config webpack.qa.js --color
