import { otherPattern, pattern } from '@musical-patterns/pattern-playroom-test'
import { StandardPatternSpecProperties } from '@musical-patterns/pattern'

const APP_URL = 'http://localhost:8081'

const VALID_TEST_MODIFICATION = '2'
const OUT_OF_RANGE_INVALID_TEST_MODIFICATION = '3'
const BAD_FORMAT_INVALID_TEST_MODIFICATION = 'e'

const PATTERN_SPEC_RANGED_PROPERTY_ONE_KEY = StandardPatternSpecProperties.PATTERN_DURATION_SCALAR
const PATTERN_SPEC_RANGED_PROPERTY_TWO_KEY = StandardPatternSpecProperties.PATTERN_PITCH_SCALAR
const PATTERN_SPEC_OPTIONED_PROPERTY_ONE_KEY = 'optionedPropertyOne'
const PATTERN_SPEC_OPTIONED_PROPERTY_TWO_KEY = 'optionedPropertyTwo'

const TEST_PATTERN_ID = pattern.patternId
const TEST_PATTERN_TITLE = pattern.metadata.formattedName
const TEST_PATTERN_SPEC_RANGED_PROPERTY_ONE_INITIAL_VALUE = pattern.initialSpec[ PATTERN_SPEC_RANGED_PROPERTY_ONE_KEY ]
const TEST_PATTERN_SPEC_RANGED_PROPERTY_TWO_INITIAL_VALUE = pattern.initialSpec[ PATTERN_SPEC_RANGED_PROPERTY_TWO_KEY ]
const TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_INITIAL_VALUE = pattern.initialSpec[ PATTERN_SPEC_OPTIONED_PROPERTY_ONE_KEY ]
const TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_MODIFIED_VALUE = pattern.specAttributes[ PATTERN_SPEC_OPTIONED_PROPERTY_ONE_KEY ].constraint[ 0 ]
const TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_INITIAL_VALUE = pattern.initialSpec[ PATTERN_SPEC_OPTIONED_PROPERTY_TWO_KEY ]
const TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_MODIFIED_VALUE = pattern.specAttributes[ PATTERN_SPEC_OPTIONED_PROPERTY_TWO_KEY ].constraint[ 1 ]

const OTHER_TEST_PATTERN_ID = otherPattern.patternId
const OTHER_TEST_PATTERN_TITLE = otherPattern.metadata.formattedName
const OTHER_TEST_PATTERN_SPEC_RANGED_PROPERTY_ONE_INITIAL_VALUE = otherPattern.initialSpec[ PATTERN_SPEC_RANGED_PROPERTY_ONE_KEY ]
const OTHER_TEST_PATTERN_SPEC_RANGED_PROPERTY_TWO_INITIAL_VALUE = otherPattern.initialSpec[ PATTERN_SPEC_RANGED_PROPERTY_TWO_KEY ]
const OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_INITIAL_VALUE = otherPattern.initialSpec[ PATTERN_SPEC_OPTIONED_PROPERTY_ONE_KEY ]
const OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_MODIFIED_VALUE = otherPattern.specAttributes[ PATTERN_SPEC_OPTIONED_PROPERTY_ONE_KEY ].constraint[ 1 ]
const OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_INITIAL_VALUE = otherPattern.initialSpec[ PATTERN_SPEC_OPTIONED_PROPERTY_TWO_KEY ]
const OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_MODIFIED_VALUE = otherPattern.specAttributes[ PATTERN_SPEC_OPTIONED_PROPERTY_TWO_KEY ].constraint[ 0 ]

const DEFAULT_VIEWPORT_WIDTH = 1600
const DEFAULT_VIEWPORT_HEIGHT = 800

const LONG_ENOUGH_FOR_TIME_TO_PASS = 100
const LONG_ENOUGH_FOR_TIME_TO_HAVE_BEEN_RESET = 100
const A_BIT_LONGER = 1000

export {
    APP_URL,
    TEST_PATTERN_ID,
    TEST_PATTERN_TITLE,
    TEST_PATTERN_SPEC_RANGED_PROPERTY_TWO_INITIAL_VALUE,
    TEST_PATTERN_SPEC_RANGED_PROPERTY_ONE_INITIAL_VALUE,
    TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_INITIAL_VALUE,
    TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_MODIFIED_VALUE,
    TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_INITIAL_VALUE,
    TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_MODIFIED_VALUE,
    OTHER_TEST_PATTERN_ID,
    OTHER_TEST_PATTERN_TITLE,
    OTHER_TEST_PATTERN_SPEC_RANGED_PROPERTY_TWO_INITIAL_VALUE,
    OTHER_TEST_PATTERN_SPEC_RANGED_PROPERTY_ONE_INITIAL_VALUE,
    OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_INITIAL_VALUE,
    OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_ONE_MODIFIED_VALUE,
    OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_INITIAL_VALUE,
    OTHER_TEST_PATTERN_SPEC_OPTIONED_PROPERTY_TWO_MODIFIED_VALUE,
    VALID_TEST_MODIFICATION,
    OUT_OF_RANGE_INVALID_TEST_MODIFICATION,
    BAD_FORMAT_INVALID_TEST_MODIFICATION,
    PATTERN_SPEC_RANGED_PROPERTY_ONE_KEY,
    PATTERN_SPEC_RANGED_PROPERTY_TWO_KEY,
    PATTERN_SPEC_OPTIONED_PROPERTY_ONE_KEY,
    PATTERN_SPEC_OPTIONED_PROPERTY_TWO_KEY,
    DEFAULT_VIEWPORT_WIDTH,
    DEFAULT_VIEWPORT_HEIGHT,
    LONG_ENOUGH_FOR_TIME_TO_PASS,
    LONG_ENOUGH_FOR_TIME_TO_HAVE_BEEN_RESET,
    A_BIT_LONGER,
}
