Makefile.playroom:
	@:

build:
	@musical-patterns-cli build "webpack --config webpack.library.js"

build_local:
	@musical-patterns-cli build "webpack --config webpack.local.js"

start:
	@musical-patterns-playroom
