export { sleep } from './sleep'
export { selectTestPattern, selectOtherTestPattern }from './selectTestPattern'
export { refreshWithTestPatternSelected, refreshPage }from './refresh'
export { elementIds, elementCount, elementExists, elementInnerText, elementValue, elementChecked } from './checkElement'
export { press } from './keyboard'
export { reset } from './reset'
export { loseFocus } from './loseFocus'
export { currentTime, totalDuration } from './getCurrentTime'
export { findElement } from './findElement'
export { simulateDesktopViewport, simulateMobileViewport } from './setViewport'
export { selectOption } from './selectOption'
